### ISSUE TITLE
Password JWT

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-point-server#128]
Needs to be done for 

- bac-rest
- https://github.com/NubeDev/bacnet-flask
- https://github.com/NubeIO/bbb-py-rest
- https://github.com/NubeDev/s-mon

# JWT
I found this one to be the best
https://flask-jwt-extended.readthedocs.io/en/stable/basic_usage/

# Storing password 

## keyring
https://pypi.org/project/keyring/

## bcrypt
https://pypi.org/project/bcrypt/

**Comment by RaiBnod** [comment]
Completed.
