### ISSUE TITLE
Add TS to MQTT payload

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-point-server#147]
![image](https://user-images.githubusercontent.com/18637436/101531011-c7a9fe00-39e6-11eb-8bbe-0d59d66a0543.png)

**Comment by Shiny380** [comment]
do you really need `fault_ts` and `cov_ts`?
the one timestamp would serve both wouldn't it?

**Comment by NubeDev** [comment]
Na better for both
Last value is like last vaild COV
And fault is last fault
