### ISSUE TITLE
Ping point

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-point-server#149]
The ping point type i think has been removed
Also we need to a way to disable this feature as its not required to do this

```
https://github.com/NubeIO/rubix-point-server/blob/master/src/source_drivers/modbus/models/device.py#L22
```

**Comment by Shiny380** [comment]
`device.ping_point`
string: `<fc>:<register>:<length>`
i.e. `4:1:2` = READ_INPUT_REGISTERS,  Address 1, length 2
No type needed.
also if it's `null` it's not used and it technically disabled
