### ISSUE TITLE
MQTT topic needs to be based of the rubix-service plat details

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-point-server#165]
This topic is for cloud services

- Add `device_id` (and maybe `client` and `site`) in the external mqtt topics.
    - subscribe to updates to these details over mqtt (`rubix-service` publishes)
- Need a way to differentiate between external and local mqtt so it's only attached to external topics

https://github.com/NubeIO/rubix-service/blob/master/src/platform/model_wires_plat.py#L5

**Comment by RaiBnod** [comment]
This one is complete, hence closing down the ticket.
