### ISSUE TITLE
MQTT offline COV issue

### ISSUE THREAD

**Issue by Shiny380** [NubeIO/rubix-point-server#174]
### Potential Issue to check
if the `cov_threshold` is high enough for the value to never change after first reading
**AND**
the MQTT is diconnected / broker is down when the first reading happens

Then the Broker will never hold a value for this point unless the mqtt library keeps unpublished messages until it reconnects to the broker
`QOS` is default 1 (at least once) there need to test if mqtt lib will store when not connected and re-send when reconnected to broker
Related #112

**Comment by RaiBnod** [comment]
Related to this: https://github.com/NubeIO/rubix-point-server/wiki/MQTT-Broker-(Mosquitto)-installation-on-Pi
