### ISSUE TITLE
New end points

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-point-server#175]
## Call all devices under a network (cant return device points)
/network/UUID/devices

## Call all points under a device 
***not needed but if if its easy***
/devices/UUID/points

**Comment by RaiBnod** [comment]
@NubeDev Is your above ticket means this:

### 1.
> **Call all devices under a network (cant return device points)**
    /network/UUID/devices

Create an extra flag where points=false for restricting the points return. As in below API:
http://localhost:1515/api/networks/uuid/<network_uuid>?with_children=true&points=false
```
{
  <network_details>,
  "devices": [
    {
      <device1_without_points>
    },
    {
      <device2_without_points>
    }
  ]
}
```

### 2.
> **Call all points under a device**
    not needed but if if its easy
    /devices/UUID/points

It seems like this one, which we already have:
http://localhost:1515/api/devices/uuid/<device_uuid>?with_children=true
```
{
  <device_details>,
  "points": [
    {
      <point_1>
    },
    {
      <point_2>
    }
  ]
}
```
