### ISSUE TITLE
Point offset is not working

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-point-server#177]
![image](https://user-images.githubusercontent.com/18637436/104785735-5c223000-57df-11eb-80aa-4f7dcfb84b04.png)

**Comment by Shiny380** [comment]
`value_offset` also has to be coupled with `value_operation`
if `value_operation` is `null` then nothing is applied.
**Operations**:
```
ADD
SUBTRACT
MULTIPLY
DIVIDE
BOOL_INVERT
```
In your example:
`value_offset` = `10`
`value_operation` = `SUBTRACT`
