### ISSUE TITLE
point write scaling

### ISSUE THREAD

**Issue by Shiny380** [NubeIO/rubix-point-server#185]
Allow for `input min/max`, `scale min/max`, `value_offset` and `value_operation` to be applied to `write_value` for `writable` **point**
```
{
    "input_min": 0,
    "input_max": 100,
    "scale_min": 0,
    "scale_max": 10
}
```
input min/max (0-100) is what can be written to for `write_value`
scale min/max (0-10) is what is actually send over the driver (i.e. modbus)

**Needs discussion:** This might have to work the opposite for `input/read-only` **points** where the `value_original` is the reading and `value` has offset and scaling applied but haven't thought any more on this.

**Comment by RaiBnod** [comment]
Scaling improvement is done.
