### ISSUE TITLE
generic point HTTP PATCH

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-point-server#187]
generic point has no support for HTTP PATCH.

Needs to be added

**Comment by Shiny380** [comment]
### Allow `write_value` to write to `generic_point`
Generic point needs to be reworked as it's general scope/function is changing
for now just implement following changes:
#### TODO:
- Change `generic_point`.`writable` to `True`
- if `write_value` is changed in `PATCH` request -> update `point_store` with `write_value`

**Comment by Shiny380** [comment]
#### Note: Check following issue
https://github.com/NubeIO/rubix-point-server/issues/189
If this issue isn't much more work it would be better to close this one and work on that instead

**Comment by RaiBnod** [comment]
Ya, sure we can close this down and work on the other ticket. The other ticket more descriptive.
