### ISSUE TITLE
GenericPoint Rework

### ISSUE THREAD

**Issue by Shiny380** [NubeIO/rubix-point-server#189]
### Generic Point
Related #187 
**Mostly discussion topic for now until full scope of generic point is decided**

Maybe two point types:
- **Writable** - i.e. set_point that can be written from cloud (Over `HTTP PATCH`)
- **Not Writable / Input Only** - i.e. data point that comes from internal service (i.e. wires, node-red) (This is the current implementation)(updated over MQTT as currently implemented)

These two should be kept separate as a `non-writable / input only` point might be coming from some new data source from node-red (example) and should not be writable by a user/cloud

**Comment by NubeDev** [comment]
I think when this is done we need the priority array aswell.
