### ISSUE TITLE
Generic Point support writing string

### ISSUE THREAD

**Issue by Shiny380** [NubeIO/rubix-point-server#215]
**Note: This is a temporary feature**
After discussion, we are adding `generic_point > type` and if `type=string` we are storing `value_raw` as string value leaving value as null and all priority array as null

maybe need support for mqtt listener aswell. i.e. if `value` in payload is string then do same as above else update as normal

**Comment by RaiBnod** [comment]
### Scope:

**Data types (Enum)**:
- int (`value` should be converted into: `integer`)
- float
- string (only store on `value_raw`, leaving `value` as `null`, `priority_array` values as `null`)
- bool (`value` should be: `0` or `1`)

Take two input parameter to PATCH value for now:

- priority_array: for data type `int`, `float`, `bool`
- value_raw: for data type `string`

Also add `nullable` `unit` field as `string`. @NubeDev request.
