### ISSUE TITLE
Update to point mapping and how to subscribe to topic's and read only 

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-point-server#265]
## example code for wires
```
    if (topicSetting === TOPIC_TYPE.POINT_NAME) {
      this.topic = `${topicCommon}/+/+/+/+/+/${pntName}`
    } else if (topicSetting === TOPIC_TYPE.POINT_UUID) {
      this.topic = `${topicCommon}/+/+/+/+/${pntUUID}/+`
    } else if (topicSetting === TOPIC_TYPE.DEVICE_NAME_AND_POINT_NAME) {
      this.topic = `${topicCommon}/+/+/+/${devName}/+/${pntName}`
    } else if (topicSetting === TOPIC_TYPE.DEVICE_UUID_AND_POINT_UUID) {
      this.topic = `${topicCommon}/+/+/${devUUID}/+/${pntUUID}/+`
    } else if (topicSetting === TOPIC_TYPE.NETWORK_NAME_DEVICE_NAME_AND_POINT_NAME) {
      this.topic = `${topicCommon}/+/${netName}/+/${devName}/+/${pntName}`
    } else if (topicSetting === TOPIC_TYPE.NETWORK_UUID_DEVICE_UUID_AND_POINT_UUID) {
      this.topic = `${topicCommon}/${netUUID}/+/${devUUID}/+/${pntUUID}/+`
    }
```
## Add same support for grafana
![image](https://user-images.githubusercontent.com/18637436/111050667-24173080-84a2-11eb-836d-0ed4749f621a.png)

### Also do small fix to grafana
![image](https://user-images.githubusercontent.com/18637436/111050754-9be55b00-84a2-11eb-90a6-d32fce7d9741.png)

![image](https://user-images.githubusercontent.com/18637436/111050812-eb2b8b80-84a2-11eb-9c3c-49562825d929.png)

## point mapping upgrades
![image](https://user-images.githubusercontent.com/18637436/111050715-54f76580-84a2-11eb-90bd-792d87dc545f.png)

**Comment by RaiBnod** [comment]
For first point subscription:

These two will be enough:
- Subscribe by Name (by default): `network.name`, `device.name`, `point.name` (We give this option as default one so copy paste will work smooth, but we need to make a better UI on frontend that name should not change easily)
- Subscribe to Point UUID: `UUID` is unique, it itself be enough so we don't need `network.uuid` and `device.uuid`

Hence it will be like this:

![image](https://user-images.githubusercontent.com/6800775/112417437-bf848d00-8d4f-11eb-8e90-f50f793a3733.png)
