### ISSUE TITLE
Math, Scaling, Rounding, and COV

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/rubix-point-server#295]
I think the order for applying transformations should be like this:
1. Apply `Math Expression`. as per https://github.com/NubeIO/lora-raw/pull/76
2. Apply `Scaling`.  as per https://github.com/NubeIO/rubix-point-server/issues/293 https://github.com/NubeIO/lora-raw/blob/e13c28810111f0a1833fb214228d5456df0ff001/src/models/model_point.py#L99
3. Apply `Rounding`.
4. THEN Check for COV. 

I think we also need to allow the user to Enable each of the value tranformations. This would probably be done with a checkbox for `Math Exp. Enable` and one for `Scaling Enable`.  It would be best if the input fields for each tranformation type were hidden when the tranformation was not enabled.  So when `Scaling Enable` is not checked the user wouldn't see `Input Min`, `Input Max`, `Scale Min`, or `Scale Max`. 

The COV check should be done after the value transformations have been applied. 

![image](https://user-images.githubusercontent.com/40550860/114320537-9a6a8980-9b59-11eb-879a-45cd77326ac7.png)

**Comment by RaiBnod** [comment]
This one is fixed.

Hence closing down the ticket.
