### ISSUE TITLE
LORA to RUBIX point mapping issues

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/rubix-point-server#296]
1. Point multi-select needs work.  The functions of the `select all` and `select all on device` interfere with each other.  In my opinion, `Select All` and `Clear All` should just be buttons (not checkboxes).  

2. `Writeable` should be enabled by default:
![image](https://user-images.githubusercontent.com/40550860/114320925-b0794980-9b5b-11eb-9ebf-e736ec4a9f34.png)

3. Values should be sent to the Rubix Points when created:
![image](https://user-images.githubusercontent.com/40550860/114321063-385f5380-9b5c-11eb-9287-986b620fbaba.png)

4. `Auto add Devices, Points, and Mappings` option doesn't work:
![image](https://user-images.githubusercontent.com/40550860/114321220-026e9f00-9b5d-11eb-9402-f1ebf6b22519.png)

**Comment by CanuckMarc** [comment]
Update:
Entering the point mapping works well, but the result in the `rubix service` has issues.

See video of the process below.  The created `rubix` points do not have `writeable` ticked, and when I try to enable it manually, it gives me errors.  Once these points are writeable, we need to confirm that the value that comes through is the correct `value` with the `math expression` applied, and not the `raw value`. 

https://www.awesomescreenshot.com/video/3469811?key=0e1361489df4a64f656179bac02a279b

**Comment by RaiBnod** [comment]
`writable` is by default `true` now and other existing issues are also fixed.

Hence, closing down this ticket.
