### ISSUE TITLE
Tags with a Key, but no Value, should be set to null

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/rubix-point-server#299]
When a Tag is added, with nothing in the `Value` field, it should default to `null`.  

Currently if there is nothing entered in the `Value` field, then the GUI removes the Tag key/value pair.

**Comment by enjuthulung** [comment]
I have tested with values "",null and 0 there is no issue in backend. 
![image](https://user-images.githubusercontent.com/18350500/114830402-dfa5ea00-9deb-11eb-881a-93e0a9a62c09.png)
Also postgres sync is working
![image](https://user-images.githubusercontent.com/18350500/114830511-006e3f80-9dec-11eb-8a40-f2359b5ccc83.png)
