### ISSUE TITLE
On point write dont poll write value again (Only write value once)

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-point-server#301]
This is needed to stop sending the same value evey poll.
This will only be for function codes  https://github.com/NubeIO/rubix-point-server/blob/eedf55cb57ed103576e0ad1fc66b2b04c18a4f9e/src/drivers/modbus/enums/point/points.py#L9

Add new field  https://github.com/NubeIO/rubix-point-server/blob/master/src/drivers/modbus/models/point.py#L14
`write_value_once` type of boolean
`write_value_once_cov` type float

- if its set to true then it will only send the value once and will keep sending if the point is in fault
- it will send a new value on cov of the write value based of the `write_value_once_cov` setting

**Comment by RaiBnod** [comment]
@NubeDev `write_value_once_cov` might not needed, this extra one changes will changes lots of codes.

What we do is:
- only one field addition `write_value_once` with type `Boolean`.
- if `priority_array_write` got changed and `write_value_once` is `True` then we will re-write again until we succeed (point_store.fault = False).
- And if `write_value_once` is `False` we keep doing write operation as in current flow.
