### ISSUE TITLE
Issues with influx tags

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/rubix-point-server#319]
**Influx Tags and Values are reversed.**  
Point tags are shown below, followed by the resulting data in influxdb.  You can see that the tag `value` is being sent as the `key`. These should be reversed.  Reversed key/value can also be seen in the excel export of the points.

![image](https://user-images.githubusercontent.com/40550860/116156225-8a909f00-a72e-11eb-96b1-92f08ab4b387.png)
![image](https://user-images.githubusercontent.com/40550860/116156249-8fede980-a72e-11eb-8d10-0204b79672f5.png)
![image](https://user-images.githubusercontent.com/40550860/116163041-56bb7680-a73a-11eb-8170-1903cffa56df.png)

**Comment by NubeDev** [comment]
Removed this for now add back in @CanuckMarc if you think its still an issue

**Other influx data issues**
fields/tags `id`, `value`, and `value_original` have deg C added as units.  There should be no units for these fields.
![image](https://user-images.githubusercontent.com/40550860/116156687-26220f80-a72f-11eb-8a94-31fe465333c3.png)
![image](https://user-images.githubusercontent.com/40550860/116156696-291d0000-a72f-11eb-9a53-8ffb0e95f002.png)
