### ISSUE TITLE
Add INTERVAL&COV option for histories

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/rubix-point-server#324]
We need to add `COV & INTERVAL` as an additional option to the rubix point `History Type`.  This configuration would save a history based on both the `COV Threshold`, and based on the `History Interval`.  

For example:
Point has `COV & INTERVAL` option selected on `History Type`.  If the value changes by the `COV threshold`, then a history is logged.  A history log is also saved at the `History Interval`, on the same point.

**Comment by CanuckMarc** [comment]
@RaiBnod The `COV & INTERVAL` option is not available in the latest builds (plat and point-server both @1.7.0)

![image](https://user-images.githubusercontent.com/40550860/118546742-b934ef00-b79b-11eb-959d-7db27c0804c9.png)

**Comment by NubeDev** [comment]
This is a UI issue @CanuckMarc

**Comment by CanuckMarc** [comment]
@RaiBnod  The `INTERVAL AND COV` option isn't working.  I have a bunch of Boolean points that are set for `COV AND INTERVAL` histories, with `History Interval` set to 60 and `COV Threshold` set to 0.  It is only getting histories logged on the `INTERVAL` (60 mins), but not when there is a COV (true-false transition).
