### ISSUE TITLE
Add point mapping by name

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-point-server#352]
Let user do point mapping by name

Mapping should only have two options 
- point UUID
- network_name/device_name/point_name

In the UI the user has the option
By defult we will use `network_name/device_name/point_name`

**Comment by CanuckMarc** [comment]
![image](https://user-images.githubusercontent.com/40550860/120121449-e2676d80-c1e6-11eb-86e4-7952062b4d90.png)

**Comment by RaiBnod** [comment]
After we've been playing with mapping much, we've a good idea on existing mapping improvements.

**Scope:**

- Add `mapping_state` for showing mapping link. Status are: `MAPPED`, `BROKEN`.
- Refactor mapping schema as this:
    ```python
    class LPGBPointMapping(ModelBase):
        """
        lora_point <> generic_point | bacnet_point
        """
        __tablename__ = 'mappings_lp_gbp'
    
        uuid = db.Column(db.String, primary_key=True)
        point_uuid = db.Column(db.String, db.ForeignKey('points.uuid'), nullable=False)
        mapped_point_uuid = db.Column(db.String(80), nullable=True, unique=True)
        point_name = db.Column(db.String(80), nullable=False)
        mapped_point_name = db.Column(db.String(80), nullable=True)
        type = db.Column(db.Enum(MapType), nullable=True) # GENERIC, BACNET
        mapping_state = db.Column(db.Enum(MappingState), nullable=True) # MAPPED, BROKEN
   ```
- Refactor POST request, It should be via uuid and name:
  - uuid: it will be called when we are doing normal mapping, we take just two uuids with `type` and fills the names dynamically
  - name: it will be called when we are doing import/export, we take just two name with `type` --name will be colon (:) delimited
- Add an API to update the `mapping_state`:
  - Change names from `uuid` if names are update
  - Update `mapping_state` as per it's current state; `BROKEN` when the mapped point is no more in the table
- Migration: delete older table and re-create table again.
