### ISSUE TITLE
Make default point mapping for temperature have default COV Threshold of 0.01

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/rubix-point-server#366]
Make default point mapping for temperature have default COV Threshold of 0.01.  Currently it is 0.1

**Comment by RaiBnod** [comment]
@CanuckMarc where is that actually. I have created a droplet on LoRa and mapped it with Rubix Generic and it's showing `COV_THRESHOLD` as `0.01`, could you please confirm?

1. LoRa Points
![image](https://user-images.githubusercontent.com/6800775/120912169-c7946d80-c6ac-11eb-99cc-056e9e04bc6c.png)


2. LoRa > Rubix Points Mapping
![image](https://user-images.githubusercontent.com/6800775/120912222-2823aa80-c6ad-11eb-9806-1289b033e973.png)

3. Created Rubix Points from Mapping
![image](https://user-images.githubusercontent.com/6800775/120912182-e09d1e80-c6ac-11eb-914a-57da8887cbe8.png)

Possibly you may have updated `COV_THRESHOLD` to `0.1` on the LoRa side before creating the mapping. Or, you have updated `COV_THRESHOLD` to `0.1` on `Rubix Points` after it's been created.

**Comment by NubeDev** [comment]
This is not a valid issue.
This could be done in wires plat maybe only if tags are used
