### ISSUE TITLE
Point Mapping Service doesn't re-connect points with the same names.  

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/rubix-point-server#399]
When `Sync` is clicked, it produces many `Broken` point mapping links.  This happens for `Modbus -> Rubix` even when the corresponding Rubix Point exists. 

To reproduce:
1. Make Modbus points.
2. Map all modbus points to Rubix Points.
3. Export Rubix Points as excel.
4. Edit excel add Tags to Rubix Points (or do nothing)
5. Delete all Rubix Points
6. Import Rubix Points from excel file. 
7. Go to `Point Mapping`  and click `Sync`
8. See that the point mapping links have become broken.

**Comment by RaiBnod** [comment]
@enjuthulung on `update_mapping_state` API let's update point-uuid via name if broken, and if still name doesn't exist leave as is as broken.
