### ISSUE TITLE
Point mapping doesn't work on adding new point mappings to existing Rubix `Device`

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/rubix-point-server#404]
The `Auto Create new device(s), point(s), and mapping(s)` option works.  But selecting an existing `Rubix Device` does not. 

![image](https://user-images.githubusercontent.com/40550860/126700580-a579df49-bfbc-461e-b7ef-70f4bc08753f.png)

**Comment by RaiBnod** [comment]
It is resolved now.
