### ISSUE TITLE
Fallback should be able to set to be null

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-point-server#415]

**Comment by NubeDev** [comment]
@CanuckMarc 
Please let us know also the defult faulback value as of now its at 16

**Comment by CanuckMarc** [comment]
The default value for `fallback` should be `null`

**Comment by RaiBnod** [comment]
Currently, the default `fallback_value=16` & in case of all priority array null, we set 16th priority array with fallback value.

For reference: https://github.com/NubeIO/rubix-point-server/issues/337#issuecomment-855330622

@NubeDev do you want to make that default `fallback_value=null`?

**Comment by NubeDev** [comment]
ya 16 is a bad number to be by default

please make it null and that it supports null
